# Generated by Django 5.1.2 on 2024-11-09 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodbank_name', models.CharField(max_length=255)),
                ('foodbank_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('id_verification', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('is_verified', models.BooleanField(default=False)),
                ('emergency_alerts_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodbank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
