# Generated by Django 5.1.2 on 2024-11-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_foodbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_alerts_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foodbank_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='response_to_emergency_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews_given',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_reservations',
        ),
        migrations.AlterField(
            model_name='profile',
            name='donation_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='donation_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
