# Generated by Django 5.1.3 on 2024-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donor_type',
            field=models.CharField(default='individual', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='donor_type',
            field=models.CharField(default='restaurant', max_length=100),
        ),
    ]
