# Generated by Django 5.1.2 on 2024-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_responsetodonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetodonation',
            name='quantity_donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
